name = "mailer-frontend"
compatibility_date = "2024-07-25"
pages_build_output_dir = ".svelte-kit/cloudflare"

[placement]
mode = "smart"

[env.preview.vars]
NODE_VERSION = "20"
PNPM_VERSION = "9"

[env.production.vars]
NODE_VERSION = "20"
PNPM_VERSION = "9"
FRONTEND_URL = "https://mailer.yannic.at"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "mailer-dev"
database_id = "01c3ff83-fa8a-432f-aee6-e437bdb2a8d3"

[[env.production.d1_databases]]
binding = "DB"
database_name = "mailer-prod"
database_id = "84f04dd9-8f7c-4463-be83-64782df4139f"