name = "mailer-frontend"
compatibility_date = "2024-10-03"
pages_build_output_dir = ".svelte-kit/cloudflare"

[placement]
mode = "smart"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "mailer-dev"
database_id = "01c3ff83-fa8a-432f-aee6-e437bdb2a8d3"

[[env.production.d1_databases]]
binding = "DB"
database_name = "mailer-prod"
database_id = "84f04dd9-8f7c-4463-be83-64782df4139f"