// Generated by Wrangler on Mon Jul 22 2024 09:49:23 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types`

interface Env {
	AWS_REGION: "eu-central-1";
	NODE_VERSION: "20";
	PNPM_VERSION: "9";
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	DB: D1Database;
}
