// Generated by Wrangler on Thu Jul 25 2024 15:16:46 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types`

interface Env {
	AWS_REGION: "eu-central-1";
	NODE_VERSION: "20";
	PNPM_VERSION: "9";
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	DB: D1Database;
}
