// Generated by Wrangler on Sun Aug 04 2024 15:23:39 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types --env dev`

interface Env {
	NODE_VERSION: "20";
	PNPM_VERSION: "9";
	AWS_REGION: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	AWS_SNS_TOPIC_ARN: string;
	DB: D1Database;
}
