#:schema node_modules/wrangler/config-schema.json
main = "src/index.ts"
compatibility_date = "2024-10-03"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[env.dev]
name = "mailer_backend_dev"
routes = [
	{ pattern = "dev.api.mailer.yannic.at", custom_domain = true }
]

[env.prod]
name = "mailer_backend_prod"
routes = [
	{ pattern = "api.mailer.yannic.at", custom_domain = true }
]

[placement]
mode = "smart"

[env.dev.vars]
AWS_REGION = "eu-central-1"
AWS_SES_CONFIGURATIONSET_NAME = "mailer_dev"
NODE_VERSION = "22"
PNPM_VERSION = "9"

[env.prod.vars]
AWS_REGION = "eu-central-1"
AWS_SES_CONFIGURATIONSET_NAME = "mailer_prod"
NODE_VERSION = "22"
PNPM_VERSION = "9"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "mailer-dev"
database_id = "01c3ff83-fa8a-432f-aee6-e437bdb2a8d3"

[[env.prod.d1_databases]]
binding = "DB"
database_name = "mailer-prod"
database_id = "84f04dd9-8f7c-4463-be83-64782df4139f"
