#:schema node_modules/wrangler/config-schema.json
name = "backend"
main = "src/index.ts"
compatibility_date = "2024-07-12"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[vars]
NODE_VERSION = "20"
PNPM_VERSION = "9"

[[d1_databases]]
binding = "DB"
database_name = "mailer-dev"
database_id = "c3351312-2e11-41bf-b3a3-38e251968ec6"
