#:schema node_modules/wrangler/config-schema.json
name = "mailer-backend"
main = "src/index.ts"
compatibility_date = "2024-07-25"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[vars]
AWS_REGION = "eu-central-1"
NODE_VERSION = "20"
PNPM_VERSION = "9"

[[d1_databases]]
binding = "DB"
database_name = "mailer-dev"
database_id = "01c3ff83-fa8a-432f-aee6-e437bdb2a8d3"
