#:schema node_modules/wrangler/config-schema.json
name = "mailer-backend"
main = "src/index.ts"
compatibility_date = "2024-07-22"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[vars]
AWS_REGION = "eu-central-1"
NODE_VERSION = "20"
PNPM_VERSION = "9"

[[d1_databases]]
binding = "DB"
database_name = "mailer-dev"
database_id = "c3351312-2e11-41bf-b3a3-38e251968ec6"
