// Generated by Wrangler on Tue Aug 06 2024 11:20:24 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types --env preview`

interface Env {
	NODE_VERSION: "20";
	PNPM_VERSION: "9";
	PUBLIC_FRONTEND_URL: "https://mailer.pages.dev";
	PUBLIC_BACKEND_URL: "https://dev-api.mailer.yannic.at";
	DB: D1Database;
}
