// Generated by Wrangler on Thu Jul 25 2024 14:10:26 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types --env preview`

interface Env {
	NODE_VERSION: "20";
	PNPM_VERSION: "9";
	FRONTEND_URL: "https://mailer.pages.dev";
	DB: D1Database;
}
