// Generated by Wrangler on Tue Aug 06 2024 11:16:32 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types --env preview`

interface Env {
	NODE_VERSION: "20";
	PNPM_VERSION: "9";
	DB: D1Database;
}
