name: CI Backend PROD

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'db/**'
      - 'lib/**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci_backend:
    name: CI Backend PROD
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Format check
        run: pnpm -w run format:check

      - name: Run tests
        run: pnpm test

      - name: Deploy prod
        run: pnpm deploy:prod
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
