name: CI Frontend DEV

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'frontend/**'
      - 'db/**'
      - 'lib/**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci_frontend:
    name: CI frontend DEV
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Format check
        run: pnpm -w run format:check

      - name: Run tests
        run: pnpm test

      - name: Deploy dev
        run: pnpm deploy:dev
        env:
          PUBLIC_FRONTEND_URL: ${{ vars.FRONTEND_URL }}
          PUBLIC_BACKEND_URL: ${{ vars.BACKEND_URL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
